apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - pdb.yaml
  - secrets.example.yaml

images:
  - name: docker.io/agslima/app-stayheathy-backend
    newTag: latest
  - name: docker.io/agslima/app-stayheathy-frontend
    newTag: latest
