apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-trivy
  annotations:
    policies.kyverno.io/title: Verify Trivy attestation
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: critical
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30

  rules:
    - name: require-trivy-attestation
      match:
        any:
          - resources:
              kinds: ["Pod", "Deployment"]
              namespaces: ["prod", "production"]
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  security.break-glass: "true"

      verifyImages:
        - imageReferences:
            - "docker.io/agslima/app-stayheathy-backend*"
            - "docker.io/agslima/app-stayheathy-frontend*"

          attestations:
            - predicateType: "https://security.sigstore.dev/attestations/vuln/trivy/v1"
              attestors:
                - entries:
                    - keyless:
                        issuer: "https://token.actions.githubusercontent.com"
                        subjectRegExp: >-
                          ^https://github.com/agslima/software-delivery-pipeline/.github/workflows/ci-release-gate\.yml@refs/(tags/v.*|heads/.*)$
