apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - database.yaml

images:
  - name: docker.io/agslima/app-stayheathy-backend
    newTag: latest
  - name: docker.io/agslima/app-stayheathy-frontend
    newTag: latest
