# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
name: Auto-merge for dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  review-and-merge:
    # Only run for Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Only approve/merge if it's a Patch or Minor update.
      # Ignore "Major" updates to review them manually.
      
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # NOTE: GitHub Actions' GITHUB_TOKEN cannot approve pull requests.
      # If approvals are required by branch protection, use a PAT and add a
      # separate step guarded by that secret.
